/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { ApiContext } from "./../config/context"
import type { FieldValidationResolver, FieldAuthorizationResolver } from "./plugins"
import type { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    date<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "DateTime";
    /**
     * A field whose value conforms to the standard internet email address format as specified in RFC822: https://www.w3.org/Protocols/rfc822/.
     */
    email<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "EmailAddress";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    date<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "DateTime";
    /**
     * A field whose value conforms to the standard internet email address format as specified in RFC822: https://www.w3.org/Protocols/rfc822/.
     */
    email<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "EmailAddress";
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  EmailAndPasswordInput: { // input type
    email: NexusGenScalars['EmailAddress']; // EmailAddress!
    password: string; // String!
  }
}

export interface NexusGenEnums {
  ErrorCode: "BAD_REQUEST" | "FORBIDDEN" | "NOT_FOUND" | "UNABLE_TO_PROCESS" | "UNAUTHORIZED"
  ErrorMessage: "FORBIDDEN_YOU_DO_NOT_HAVE_ACCESS_TO_THIS_RESOURCE" | "RESOURCE_NOT_FOUND" | "UNABLE_TO_PROCESS_REQUEST_DUE_TO_CLIENT_ERROR" | "UNABLE_TO_PROCESS_REQUEST_DUE_TO_SERVER_ERROR" | "UNAUTHENTICATED_PLEASE_LOGIN"
  UserStatus: "ACTIVE" | "BANNED" | "DELETED"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
  EmailAddress: any
}

export interface NexusGenObjects {
  Account: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    email?: NexusGenScalars['EmailAddress'] | null; // EmailAddress
    id?: number | null; // Int
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    verifiedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  ActiveUser: { // root type
    email?: string | null; // String
    id?: number | null; // Int
    name?: string | null; // String
    status?: NexusGenEnums['UserStatus'] | null; // UserStatus
  }
  BannedUser: { // root type
    banReason?: string | null; // String
    id?: number | null; // Int
    name?: string | null; // String
    status?: NexusGenEnums['UserStatus'] | null; // UserStatus
  }
  BooleanResult: { // root type
    success?: boolean | null; // Boolean
  }
  DeletedUser: { // root type
    deletedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: number | null; // Int
    name?: string | null; // String
    status?: NexusGenEnums['UserStatus'] | null; // UserStatus
  }
  InvalidArgument: { // root type
    key: string; // String!
    message: string; // String!
  }
  InvalidArgumentsError: { // root type
    invalidArguments: Array<NexusGenRootTypes['InvalidArgument'] | null>; // [InvalidArgument]!
  }
  Mutation: {};
  NotFoundError: {};
  Post: { // root type
    content?: string | null; // String
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: number | null; // Int
    published?: boolean | null; // Boolean
    title?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  Query: {};
  UnableToProcessError: {};
  UserAuthenticationError: {};
  UserForbiddenError: {};
}

export interface NexusGenInterfaces {
  Node: NexusGenRootTypes['Account'] | NexusGenRootTypes['ActiveUser'] | NexusGenRootTypes['BannedUser'] | NexusGenRootTypes['DeletedUser'] | NexusGenRootTypes['Post'];
  User: NexusGenRootTypes['ActiveUser'] | NexusGenRootTypes['BannedUser'] | NexusGenRootTypes['DeletedUser'];
}

export interface NexusGenUnions {
  AccountResult: NexusGenRootTypes['Account'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['UnableToProcessError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  CreateAccountResult: NexusGenRootTypes['Account'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['UnableToProcessError'];
  DeleteAccountResult: NexusGenRootTypes['BooleanResult'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['UserAuthenticationError'];
  LostPasswordResult: NexusGenRootTypes['BooleanResult'] | NexusGenRootTypes['NotFoundError'];
  ModifyEmailResult: NexusGenRootTypes['Account'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['UnableToProcessError'] | NexusGenRootTypes['UserAuthenticationError'];
  ModifyPasswordResult: NexusGenRootTypes['Account'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['UserAuthenticationError'];
  PostResult: NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['Post'] | NexusGenRootTypes['UserAuthenticationError'];
  ResetPasswordResult: NexusGenRootTypes['BooleanResult'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['UnableToProcessError'];
  SendVerificationEmailResult: NexusGenRootTypes['BooleanResult'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['UnableToProcessError'];
  SignInResult: NexusGenRootTypes['Account'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['UnableToProcessError'];
  SignOutResult: NexusGenRootTypes['BooleanResult'] | NexusGenRootTypes['UserAuthenticationError'];
  UserResult: NexusGenRootTypes['ActiveUser'] | NexusGenRootTypes['BannedUser'] | NexusGenRootTypes['DeletedUser'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['UserAuthenticationError'];
  VerifyUserResult: NexusGenRootTypes['BooleanResult'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['UnableToProcessError'];
}

export type NexusGenRootTypes = NexusGenInterfaces & NexusGenObjects & NexusGenUnions

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  Account: { // field return type
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    email: NexusGenScalars['EmailAddress'] | null; // EmailAddress
    id: number | null; // Int
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
    verifiedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  ActiveUser: { // field return type
    email: string | null; // String
    id: number | null; // Int
    name: string | null; // String
    posts: Array<NexusGenRootTypes['Post'] | null> | null; // [Post]
    status: NexusGenEnums['UserStatus'] | null; // UserStatus
  }
  BannedUser: { // field return type
    banReason: string | null; // String
    id: number | null; // Int
    name: string | null; // String
    status: NexusGenEnums['UserStatus'] | null; // UserStatus
  }
  BooleanResult: { // field return type
    success: boolean | null; // Boolean
  }
  DeletedUser: { // field return type
    deletedAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: number | null; // Int
    name: string | null; // String
    status: NexusGenEnums['UserStatus'] | null; // UserStatus
  }
  InvalidArgument: { // field return type
    key: string; // String!
    message: string; // String!
  }
  InvalidArgumentsError: { // field return type
    code: NexusGenEnums['ErrorCode']; // ErrorCode!
    invalidArguments: Array<NexusGenRootTypes['InvalidArgument'] | null>; // [InvalidArgument]!
    message: NexusGenEnums['ErrorMessage']; // ErrorMessage!
  }
  Mutation: { // field return type
    changeUserStatus: NexusGenRootTypes['UserResult'] | null; // UserResult
    createAccount: NexusGenRootTypes['CreateAccountResult'] | null; // CreateAccountResult
    createPost: NexusGenRootTypes['PostResult'] | null; // PostResult
    createUser: NexusGenRootTypes['UserResult'] | null; // UserResult
    deleteAccount: NexusGenRootTypes['DeleteAccountResult'] | null; // DeleteAccountResult
    lostPassword: NexusGenRootTypes['LostPasswordResult'] | null; // LostPasswordResult
    modifyEmail: NexusGenRootTypes['ModifyEmailResult'] | null; // ModifyEmailResult
    modifyPassword: NexusGenRootTypes['ModifyPasswordResult'] | null; // ModifyPasswordResult
    resetPassword: NexusGenRootTypes['ResetPasswordResult'] | null; // ResetPasswordResult
    sendVerificationEmail: NexusGenRootTypes['SendVerificationEmailResult'] | null; // SendVerificationEmailResult
    signIn: NexusGenRootTypes['SignInResult'] | null; // SignInResult
    signOut: NexusGenRootTypes['SignOutResult'] | null; // SignOutResult
    verifyUser: NexusGenRootTypes['VerifyUserResult'] | null; // VerifyUserResult
  }
  NotFoundError: { // field return type
    code: NexusGenEnums['ErrorCode']; // ErrorCode!
    message: NexusGenEnums['ErrorMessage']; // ErrorMessage!
  }
  Post: { // field return type
    author: NexusGenRootTypes['User'] | null; // User
    content: string | null; // String
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: number | null; // Int
    published: boolean | null; // Boolean
    title: string | null; // String
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  Query: { // field return type
    userById: NexusGenRootTypes['UserResult'] | null; // UserResult
    users: Array<NexusGenRootTypes['UserResult'] | null> | null; // [UserResult]
  }
  UnableToProcessError: { // field return type
    code: NexusGenEnums['ErrorCode']; // ErrorCode!
    message: NexusGenEnums['ErrorMessage']; // ErrorMessage!
  }
  UserAuthenticationError: { // field return type
    code: NexusGenEnums['ErrorCode']; // ErrorCode!
    message: NexusGenEnums['ErrorMessage']; // ErrorMessage!
  }
  UserForbiddenError: { // field return type
    code: NexusGenEnums['ErrorCode']; // ErrorCode!
    message: NexusGenEnums['ErrorMessage']; // ErrorMessage!
  }
  Node: { // field return type
    id: number | null; // Int
  }
  User: { // field return type
    name: string | null; // String
    status: NexusGenEnums['UserStatus'] | null; // UserStatus
  }
}

export interface NexusGenFieldTypeNames {
  Account: { // field return type name
    createdAt: 'DateTime'
    email: 'EmailAddress'
    id: 'Int'
    updatedAt: 'DateTime'
    verifiedAt: 'DateTime'
  }
  ActiveUser: { // field return type name
    email: 'String'
    id: 'Int'
    name: 'String'
    posts: 'Post'
    status: 'UserStatus'
  }
  BannedUser: { // field return type name
    banReason: 'String'
    id: 'Int'
    name: 'String'
    status: 'UserStatus'
  }
  BooleanResult: { // field return type name
    success: 'Boolean'
  }
  DeletedUser: { // field return type name
    deletedAt: 'DateTime'
    id: 'Int'
    name: 'String'
    status: 'UserStatus'
  }
  InvalidArgument: { // field return type name
    key: 'String'
    message: 'String'
  }
  InvalidArgumentsError: { // field return type name
    code: 'ErrorCode'
    invalidArguments: 'InvalidArgument'
    message: 'ErrorMessage'
  }
  Mutation: { // field return type name
    changeUserStatus: 'UserResult'
    createAccount: 'CreateAccountResult'
    createPost: 'PostResult'
    createUser: 'UserResult'
    deleteAccount: 'DeleteAccountResult'
    lostPassword: 'LostPasswordResult'
    modifyEmail: 'ModifyEmailResult'
    modifyPassword: 'ModifyPasswordResult'
    resetPassword: 'ResetPasswordResult'
    sendVerificationEmail: 'SendVerificationEmailResult'
    signIn: 'SignInResult'
    signOut: 'SignOutResult'
    verifyUser: 'VerifyUserResult'
  }
  NotFoundError: { // field return type name
    code: 'ErrorCode'
    message: 'ErrorMessage'
  }
  Post: { // field return type name
    author: 'User'
    content: 'String'
    createdAt: 'DateTime'
    id: 'Int'
    published: 'Boolean'
    title: 'String'
    updatedAt: 'DateTime'
  }
  Query: { // field return type name
    userById: 'UserResult'
    users: 'UserResult'
  }
  UnableToProcessError: { // field return type name
    code: 'ErrorCode'
    message: 'ErrorMessage'
  }
  UserAuthenticationError: { // field return type name
    code: 'ErrorCode'
    message: 'ErrorMessage'
  }
  UserForbiddenError: { // field return type name
    code: 'ErrorCode'
    message: 'ErrorMessage'
  }
  Node: { // field return type name
    id: 'Int'
  }
  User: { // field return type name
    name: 'String'
    status: 'UserStatus'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    changeUserStatus: { // args
      id: number; // Int!
      status: NexusGenEnums['UserStatus']; // UserStatus!
    }
    createAccount: { // args
      account: NexusGenInputs['EmailAndPasswordInput']; // EmailAndPasswordInput!
    }
    createPost: { // args
      authorEmail: string; // String!
      content?: string | null; // String
      title: string; // String!
    }
    createUser: { // args
      email: string; // String!
      name: string; // String!
    }
    deleteAccount: { // args
      confirmPassword: string; // String!
    }
    lostPassword: { // args
      email: string; // String!
    }
    modifyEmail: { // args
      email: string; // String!
    }
    modifyPassword: { // args
      newPassword: string; // String!
      password: string; // String!
    }
    resetPassword: { // args
      newPassword: string; // String!
      token: string; // String!
    }
    sendVerificationEmail: { // args
      email: string; // String!
    }
    signIn: { // args
      account: NexusGenInputs['EmailAndPasswordInput']; // EmailAndPasswordInput!
    }
    verifyUser: { // args
      token: string; // String!
    }
  }
  Query: {
    userById: { // args
      id: string; // ID!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
  AccountResult: "Account" | "InvalidArgumentsError" | "NotFoundError" | "UnableToProcessError" | "UserAuthenticationError" | "UserForbiddenError"
  CreateAccountResult: "Account" | "InvalidArgumentsError" | "UnableToProcessError"
  DeleteAccountResult: "BooleanResult" | "InvalidArgumentsError" | "NotFoundError" | "UserAuthenticationError"
  LostPasswordResult: "BooleanResult" | "NotFoundError"
  ModifyEmailResult: "Account" | "InvalidArgumentsError" | "UnableToProcessError" | "UserAuthenticationError"
  ModifyPasswordResult: "Account" | "InvalidArgumentsError" | "NotFoundError" | "UserAuthenticationError"
  PostResult: "InvalidArgumentsError" | "Post" | "UserAuthenticationError"
  ResetPasswordResult: "BooleanResult" | "InvalidArgumentsError" | "UnableToProcessError"
  SendVerificationEmailResult: "BooleanResult" | "InvalidArgumentsError" | "NotFoundError" | "UnableToProcessError"
  SignInResult: "Account" | "InvalidArgumentsError" | "NotFoundError" | "UnableToProcessError"
  SignOutResult: "BooleanResult" | "UserAuthenticationError"
  UserResult: "ActiveUser" | "BannedUser" | "DeletedUser" | "InvalidArgumentsError" | "NotFoundError" | "UserAuthenticationError"
  VerifyUserResult: "BooleanResult" | "InvalidArgumentsError" | "NotFoundError" | "UnableToProcessError"
  Node: "Account" | "ActiveUser" | "BannedUser" | "DeletedUser" | "Post"
  User: "ActiveUser" | "BannedUser" | "DeletedUser"
}

export interface NexusGenTypeInterfaces {
  Account: "Node"
  ActiveUser: "Node" | "User"
  BannedUser: "Node" | "User"
  DeletedUser: "Node" | "User"
  Post: "Node"
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = keyof NexusGenInterfaces;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = keyof NexusGenUnions;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = "Account" | "ActiveUser" | "BannedUser" | "BooleanResult" | "DeletedUser" | "InvalidArgumentsError" | "NotFoundError" | "Post" | "UnableToProcessError" | "UserAuthenticationError" | "UserForbiddenError";

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: true
    __typename: false
    resolveType: false
  }
}

export interface NexusGenTypes {
  context: ApiContext;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
    /**
     * Validation for an individual field. Returning "undefined"
     * or "Promise<undefined>" means the field can be accessed.
     * Returning InvalidArgumentsError or "Promise<InvalidArgumentsError>" will prevent the resolver from executing.
     */
    validation?: FieldValidationResolver<TypeName, FieldName>
    /**
     * Authorization for an individual field. Returning "undefined"
     * or "Promise<undefined>" means the field can be accessed.
     * Returning "UserAuthenticationError" will prevent the resolver from executing.
     */
    authorization?: FieldAuthorizationResolver<TypeName, FieldName>
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}